Add remove endpoint
Alfa-Tron/java-filmorate pull request #13
Opened 2023-05-04 11:04 UTC by Vachagan-O

2023-05-06 07:15 UTC, Alfa-Tron approved these changes

2023-05-06 07:15 UTC, Alfa-Tron approved these changes

2023-05-06 08:39 UTC, fancestyao approved these changes

2023-05-06 12:57 UTC, IrinaGross approved these changes

2023-05-06 14:27 UTC, IrinaGross requested changes

2023-05-06 14:27 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public void deleteFilm(int filmId) {
В схеме можно указать ON DELETE CASCADE и этот метод станет чище. Достаточно будет удалить только фильм

2023-05-06 14:27 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public void deleteUser(int userId) {
В схеме можно указать ON DELETE CASCADE и этот метод станет чище. Достаточно будет удалить только пользователя

2023-05-07 15:16 UTC, IrinaGross approved these changes

2023-05-08 09:49 UTC, Alfa-Tron approved these changes

2023-05-08 11:27 UTC, closed without merging