Add feed
Alfa-Tron/java-filmorate pull request #16
Opened 2023-05-06 17:02 UTC by Rasperg

Реализована функциональность «Лента событий».

2023-05-06 17:37 UTC, Alfa-Tron approved these changes

2023-05-07 06:53 UTC, IrinaGross requested changes

2023-05-07 06:53 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public UserController(@Qualifier("userService") UserService userService, @Qualifier("feedService") FeedService feedService) {
Можешь использовать `@RequiredArgsConstructor`. `@Qualifier` в данном случае можно не писать

2023-05-07 06:53 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private FeedService feedService;
Сделай поля final

2023-05-07 06:53 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +public class FeedService {
Выдели в интерфейс. [Почему нужен интерфейс](https://stackoverflow.com/questions/9446502/dependency-injection-using-interfaces)

2023-05-07 06:53 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    public FeedService(@Qualifier("userDbStorage") UserStorage userStorage, @Qualifier("feedDbStorage") FeedStorage feedStorage) {
Можешь использовать `@RequiredArgsConstructor`

2023-05-07 06:53 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    private final FeedStorage feedStorage;
`@Qualifier` из конструктора укажи над полями

2023-05-07 06:53 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewServiceImpl.java
> +        Review review = repository.getReviewById(reviewId);
Тут у тебя 2 раза вызывается `repository.getReviewById(reviewId)`. Перенеси сюда логику из `checkReview`, а cам вызов  `checkReview` в этом месте можешь удалить

2023-05-07 09:33 UTC, Rasperg commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +public class FeedService {
Есть интерфейс FeedStorage

2023-05-07 14:47 UTC, IrinaGross requested changes

2023-05-07 14:47 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +public class FeedService {
Имеется в виду, что для сервиса тоже нужен интерфейс

2023-05-07 14:47 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> -@Component
Почему удалил аннотацию?

2023-05-07 14:47 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> -@Component
Почему удалил аннотацию? Вмешиваться таким образом в код - моветон. Чтобы DI знал, какой из имплементаций интерфейса нужен используется аннотация `@Qualifier`

2023-05-07 14:52 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> -@Component
В принципе вмешиваться в код, который тебе не требуется менять - моветон. Ты молодец, за тобой такого не замечено)

2023-05-08 15:56 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("feedDbStorage")
Это лишнее, но если проект запускается, то можно оставить

2023-05-08 15:58 UTC, IrinaGross requested changes
Супер, есть одно небольшое замечание

2023-05-08 15:58 UTC, IrinaGross commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final FeedServiceImpl feedServiceImpl;
private final FeedService feedServiceImpl;

2023-05-08 17:26 UTC, Rasperg commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("feedDbStorage")
Поправил

2023-05-08 17:26 UTC, Rasperg commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final FeedServiceImpl feedServiceImpl;
поправил

2023-05-08 22:30 UTC, Andrew-Voro approved these changes

2023-05-09 05:27 UTC, IrinaGross approved these changes

2023-05-09 07:57 UTC, Vachagan-O approved these changes

2023-05-09 07:59 UTC, merged